apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-a-replicaset
spec:
  selector:
    matchLabels:
      app: server-a
  replicas: 2
  template:
    metadata:
      labels:
        app: server-a
    spec:
      containers:
        - name: server-a
          image: docker-compose-server_a:latest
          ports:
            - containerPort: 3001
          imagePullPolicy: Never