apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-b-replicaset
spec:
  selector:
    matchLabels:
      app: server-b
  replicas: 2
  template:
    metadata:
      labels:
        app: server-b
    spec:
      containers:
        - name: server-b
          image: docker-compose-server_b:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001