apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-c-replicaset
spec:
  selector:
    matchLabels:
      app: server-c
  replicas: 2
  template:
    metadata:
      labels:
        app: server-c
    spec:
      containers:
        - name: server-c
          image: docker-compose-server_c:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
