apiVersion: v1
kind: Service
metadata:
  name: server-c-service
spec:
  selector:
    app: server-c
  ports:
    - port: 3003
      targetPort: 3003
      # nodePort: 30009
      protocol: TCP
  # type: NodePort //commenting because of using ingress
  type: ClusterIP