apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-c-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-c
  template:
    metadata:
      labels:
        app: server-c
    spec:
      containers:
        - name: server-c
          image: docker-compose-server_c:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: app-secret
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: my-pvc
    