version: '3.8'

services:
  server_a:
    build: ../serverA
    networks:
      - mynetwork
    # ports:
    #   - '3001:3001'

  server_b:
    build: ../serverB
    networks:
      - mynetwork
    # ports:
    #   - '3002:3002'
    depends_on:
      - server_a

  server_c:
    build: ../serverC
    networks:
      - mynetwork
    ports:
      - '3003:3003'
    depends_on:
      - server_a
      - server_b

  front:
    build: ../frontend
    networks:
      - mynetwork
    ports:
      - '5000:5000'
    depends_on:
      - server_c

networks:
  mynetwork:
    driver: bridge
