apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 50Mi  # 50MB of storage
  accessModes:
    - ReadWriteOnce  # Only one pod can write at a time
  persistentVolumeReclaimPolicy: Retain  # Keeps the data even if the PV is deleted
  hostPath:
    path: "/mnt/data"  # Path on the Kubernetes node
