apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      imagePullPolicy: Never
      image: docker-compose-front:latest
      ports:
        - containerPort: 5000
