apiVersion: v1
kind: Pod
metadata:
  name: server-a-pod
  labels:
    app: server-a
spec:
  containers:
    - name: server-a
      image: docker-compose-server_a:latest
      ports:
        - containerPort: 3001
      imagePullPolicy: Never
