apiVersion: v1
kind: Pod
metadata:
  name: server-b-pod
  labels:
    app: server-b
spec:
  containers:
    - name: server-b
      image: docker-compose-server_b:latest
      ports:
        - containerPort: 3002
      imagePullPolicy: Never
